server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_shiro
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  check-config-location: true